### ISSUE TITLE
Lista Milestone

### ISSUE THREAD

**Issue by ZahidRamirez00** [ZahidRamirez00/agenzia-viaggio-mvc#1]
- [x] Pagina iniziale
- [x] Database Cards_Tours
- [ ] Update/Create new Tour
- [x] Controller
- [x] Implementazione sistema EF
